version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: fraies
    volumes:
      - ./mongo:/data/db